using System;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace TiaMcpServer.ModelContextProtocol
{
    /// <summary>
    /// The source of a WinCC Unified script module: splitting what TIA Portal exports, building what
    /// it imports, and telling a faithful import from a mangled one. No TIA Portal types in here, so
    /// the tests can use it without the Siemens assemblies. What Openness does with these files is
    /// written down in Siemens/Portal.Unified.Scripts.cs.
    /// </summary>
    public static class UnifiedScriptCode
    {
        public const string MarkerText = "***End of Global definition area***";

        private static readonly string Marker =
            "/*<auto-generated>\r\n" + MarkerText + "\r\n" +
            "Changes to this comment may cause incorrect behavior during document based import.\r\n</auto-generated>*/";

        private static readonly Regex MarkerPattern = new Regex(
            @"/\*<auto-generated>\s*" + Regex.Escape(MarkerText) + @"[\s\S]*?</auto-generated>\*/", RegexOptions.Compiled);

        public static readonly Regex ExportedFunctionPattern = new Regex(
            @"\bexport\s+(?:async\s+)?function\s*\*?\s*([A-Za-z_$][\w$]*)\s*\(([^)]*)\)", RegexOptions.Compiled);

        private static readonly Regex DefaultParameterPattern = new Regex(@"\([^()]*\w\s*=[^=>][^()]*\)", RegexOptions.Compiled);

        public static readonly Regex ModuleNamePattern = new Regex(@"^[\p{L}_][\p{L}\p{N}_ ]*$", RegexOptions.Compiled);

        public static UnifiedScriptModuleInfo Describe(string name, string code)
        {
            var (global, functions) = Split(code);

            return new UnifiedScriptModuleInfo
            {
                Name = name,
                GlobalDefinitions = global,
                Functions = functions,
                ExportedFunctions = ExportedFunctionPattern.Matches(StripComments(functions))
                    .Cast<Match>()
                    .Select(m => $"{m.Groups[1].Value}({Regex.Replace(m.Groups[2].Value.Trim(), @"\s+", " ")})")
                    .ToList()
            };
        }

        /// <summary>Splits the file at the marker; without one everything counts as functions.</summary>
        public static (string Global, string Functions) Split(string code)
        {
            var marker = MarkerPattern.Match(code);

            if (!marker.Success)
            {
                return (string.Empty, code.Trim());
            }

            return (code.Substring(0, marker.Index).Trim(), code.Substring(marker.Index + marker.Length).Trim());
        }

        public static string Build(string? global, string? functions)
        {
            var code = new StringBuilder();

            if (!string.IsNullOrWhiteSpace(global))
            {
                code.Append(ToCrLf(global!.Trim())).Append("\r\n");
            }

            code.Append(Marker).Append("\r\n");

            if (!string.IsNullOrWhiteSpace(functions))
            {
                code.Append(ToCrLf(functions!.Trim())).Append("\r\n");
            }

            return code.ToString();
        }

        private static string ToCrLf(string text)
        {
            return text.Replace("\r\n", "\n").Replace("\r", "\n").Replace("\n", "\r\n");
        }

        /// <summary>The code without comments, as far as strings allow telling them apart.</summary>
        public static string StripComments(string code, bool dropWhitespace = false)
        {
            var result = new StringBuilder(code.Length);
            var i = 0;

            while (i < code.Length)
            {
                var c = code[i];

                if (c == '"' || c == '\'' || c == '`')
                {
                    var start = i++;

                    while (i < code.Length && code[i] != c)
                    {
                        i += code[i] == '\\' ? 2 : 1;
                    }

                    i = Math.Min(i + 1, code.Length);
                    result.Append(code, start, i - start);
                }
                else if (c == '/' && i + 1 < code.Length && code[i + 1] == '/')
                {
                    while (i < code.Length && code[i] != '\n')
                    {
                        i++;
                    }
                }
                else if (c == '/' && i + 1 < code.Length && code[i + 1] == '*')
                {
                    var end = code.IndexOf("*/", i + 2, StringComparison.Ordinal);

                    i = end < 0 ? code.Length : end + 2;
                    result.Append(' ');
                }
                else
                {
                    if (!(dropWhitespace && char.IsWhiteSpace(c)))
                    {
                        result.Append(c);
                    }

                    i++;
                }
            }

            return result.ToString();
        }

        /// <summary>What two pieces of code have to share to count as the same: no comments, no whitespace outside strings.</summary>
        public static string Normalize(string code)
        {
            return StripComments(code, dropWhitespace: true);
        }

        /// <summary>Null when the stored code is the code that was sent, ignoring comments and spacing.</summary>
        public static string? DescribeDifference(string wantedGlobal, string wantedFunctions, string storedGlobal, string storedFunctions)
        {
            // A comment that TIA Portal moved from the functions up into the global part does not
            // change the code, so the two parts are compared as the code they hold.
            if (Normalize(wantedGlobal) == Normalize(storedGlobal)
                && Normalize(wantedFunctions) == Normalize(storedFunctions))
            {
                return null;
            }

            var hint = DefaultParameterPattern.IsMatch(StripComments(wantedGlobal + "\n" + wantedFunctions))
                ? " A default parameter value (f(a, b = 5)) is not supported: set it inside the function."
                : " The code probably has a syntax error or a construct that the script parser of TIA Portal does not know.";

            return $"stored functions: {Shorten(storedFunctions)}; stored global definitions: {Shorten(storedGlobal)}.{hint}";
        }

        private static string Shorten(string text)
        {
            var oneLine = Regex.Replace(text, @"\s+", " ").Trim();

            return oneLine.Length <= 300 ? $"'{oneLine}'" : $"'{oneLine.Substring(0, 300)}...'";
        }
    }
}
