using System.Linq;
using TiaMcpServer.ModelContextProtocol;

namespace TiaMcpServer.Test
{
    /// <summary>
    /// Tests for the script modules of WinCC Unified: splitting what TIA Portal exports, building
    /// what it imports, and telling a faithful import from a mangled one. The samples are in the
    /// form TIA Portal V21 writes (exported 2026-10-06). These tests do not connect to TIA Portal.
    /// </summary>
    [TestClass]
    public class Test17UnifiedScripts
    {
        private const string Marker = "/*<auto-generated>\r\n***End of Global definition area***\r\nChanges to this comment may cause incorrect behavior during document based import.\r\n</auto-generated>*/";

        // The module TestGlobalModule of the test project, with the comments shortened.
        private const string Sample =
            "// ==========================================\r\n" +
            "// Global definitions (Global Definition)\r\n" +
            "// ==========================================\r\n" +
            "const TEMPLATE_PREFIX = \"LogEntry_\";\r\n" +
            "let executionCounter = 0;\r\n" +
            Marker + "\r\n" +
            "export function GenerateLogName(baseName) {\r\n" +
            "    executionCounter++;\r\n" +
            "    return TEMPLATE_PREFIX + baseName + \"_\" + executionCounter;\r\n" +
            "}\r\n" +
            "export function CalculateBufferOffset(startIndex, offsetMultiplier) {\r\n" +
            "   let result = startIndex + (offsetMultiplier * 10);\r\n" +
            "    return result;\r\n" +
            "}\r\n";

        [TestMethod]
        public void Test_1700_SplitScriptCode_SeparatesGlobalDefinitionsFromFunctions()
        {
            var (global, functions) = UnifiedScriptCode.Split(Sample);

            StringAssert.Contains(global, "const TEMPLATE_PREFIX");
            StringAssert.Contains(global, "let executionCounter");
            Assert.IsFalse(global.Contains("export function"));
            Assert.IsTrue(functions.StartsWith("export function GenerateLogName"));
            Assert.IsFalse(functions.Contains("auto-generated"));
        }

        [TestMethod]
        public void Test_1701_SplitScriptCode_EmptyModuleHasNothingOnEitherSide()
        {
            var (global, functions) = UnifiedScriptCode.Split("\r\n" + Marker + "\r\n");

            Assert.AreEqual(string.Empty, global);
            Assert.AreEqual(string.Empty, functions);
        }

        [TestMethod]
        public void Test_1702_SplitScriptCode_WithoutMarkerEverythingIsFunctions()
        {
            var (global, functions) = UnifiedScriptCode.Split("export function A() { return 1; }");

            Assert.AreEqual(string.Empty, global);
            Assert.AreEqual("export function A() { return 1; }", functions);
        }

        [TestMethod]
        public void Test_1703_BuildScriptCode_RoundTripsThroughSplit()
        {
            var code = UnifiedScriptCode.Build("const K = 1;\nlet n = 0;", "export function F(a) {\n  return a + K;\n}");
            var (global, functions) = UnifiedScriptCode.Split(code);

            Assert.AreEqual("const K = 1;\r\nlet n = 0;", global);
            Assert.AreEqual("export function F(a) {\r\n  return a + K;\r\n}", functions);
            Assert.IsFalse(code.Replace("\r\n", string.Empty).Contains("\n"), "Line endings are CRLF throughout");
        }

        [TestMethod]
        public void Test_1704_BuildScriptCode_WithoutGlobalDefinitionsStartsWithTheMarker()
        {
            var code = UnifiedScriptCode.Build(null, "export function F() { return 1; }");

            Assert.IsTrue(code.StartsWith("/*<auto-generated>"));
            Assert.IsTrue(code.EndsWith("export function F() { return 1; }\r\n"));
        }

        [TestMethod]
        public void Test_1705_DescribeScriptModule_ListsExportedFunctionsWithParameters()
        {
            var info = UnifiedScriptCode.Describe("TestGlobalModule", Sample);

            CollectionAssert.AreEqual(
                new[] { "GenerateLogName(baseName)", "CalculateBufferOffset(startIndex, offsetMultiplier)" },
                info.ExportedFunctions);
        }

        [TestMethod]
        public void Test_1706_DescribeScriptModule_IgnoresFunctionsInComments()
        {
            var info = UnifiedScriptCode.Describe("M",
                "// export function Old() {}\r\n" + Marker + "\r\n/* export function Older() {} */\r\nexport function Live(x) { return x; }\r\nfunction helper() {}\r\n");

            CollectionAssert.AreEqual(new[] { "Live(x)" }, info.ExportedFunctions);
        }

        [TestMethod]
        public void Test_1707_StripScriptComments_KeepsCommentMarkersInsideStrings()
        {
            var stripped = UnifiedScriptCode.StripComments("const u = \"http://x\"; // gone\r\nconst v = '/* kept */'; /* gone */ let w = `a // b`;");

            StringAssert.Contains(stripped, "\"http://x\"");
            StringAssert.Contains(stripped, "'/* kept */'");
            StringAssert.Contains(stripped, "`a // b`");
            Assert.IsFalse(stripped.Contains("gone"));
        }

        [TestMethod]
        public void Test_1708_StripScriptComments_HandlesEscapedQuotes()
        {
            var stripped = UnifiedScriptCode.StripComments("const s = \"a\\\"//b\"; // gone");

            StringAssert.Contains(stripped, "\"a\\\"//b\"");
            Assert.IsFalse(stripped.Contains("gone"));
        }

        [TestMethod]
        public void Test_1709_DescribeScriptDifference_ReformattingIsNotADifference()
        {
            // What TIA Portal wrote back for 'export function F(x) { return x + A; }'.
            var difference = UnifiedScriptCode.DescribeDifference(
                "const A = 1;", "export function F(x) { return x + A; }",
                "const A = 1;", "export function F(x) { return x + A; \r\n}");

            Assert.IsNull(difference);
        }

        [TestMethod]
        public void Test_1710_DescribeScriptDifference_MovedCommentIsNotADifference()
        {
            // TIA Portal moved '// line comment before B' above the marker.
            var difference = UnifiedScriptCode.DescribeDifference(
                "", "// line comment before B\r\nexport function B() { return 1; }",
                "// line comment before B", "export function B() { return 1; \r\n}");

            Assert.IsNull(difference);
        }

        [TestMethod]
        public void Test_1711_DescribeScriptDifference_DefaultParameterIsCaughtAndExplained()
        {
            // Stored as 'y___2' by TIA Portal.
            var difference = UnifiedScriptCode.DescribeDifference(
                "", "export function A(x, y = 2) { return x + y; }",
                "", "export function A(x, y___2) { return x + y; \r\n}");

            Assert.IsNotNull(difference);
            StringAssert.Contains(difference, "y___2");
            StringAssert.Contains(difference, "default parameter");
        }

        [TestMethod]
        public void Test_1712_DescribeScriptDifference_LostFunctionBodyIsCaught()
        {
            // A syntax error comes back as an empty function.
            var difference = UnifiedScriptCode.DescribeDifference(
                "", "export function H( { return ;;; ",
                "", "export function H(__return____) {\r\n\r\n}");

            Assert.IsNotNull(difference);
            StringAssert.Contains(difference, "syntax error");
        }

        [TestMethod]
        public void Test_1713_DescribeScriptDifference_ChangedLiteralIsCaught()
        {
            var difference = UnifiedScriptCode.DescribeDifference("", "export function A() { return \"a b\"; }", "", "export function A() { return \"a  b\"; }");

            Assert.IsNotNull(difference, "Spacing inside a string literal is code, not formatting");
        }
    }
}
