# Writes docs\tools\*.md, one page per area of tools, from the tool definitions the server publishes.
# The descriptions in the code are the source of truth; do not edit the pages by hand - change the
# Description attributes and run this again.
#
#   powershell -NoProfile -ExecutionPolicy Bypass -File tools\make-tool-docs.ps1
#
# It starts the built server through mcp-call.ps1 (-DumpTools), so it reads the running TIA Portal's
# project list only through 'tools/list' - no project is opened or changed. Run tools\finish.ps1 first.
param(
    [string]$OutDir = (Join-Path $PSScriptRoot '..\docs\tools'),
    [string]$Scratch = (Join-Path $env:TEMP 'tia-mcp-tools.jsonl')
)

& (Join-Path $PSScriptRoot 'mcp-call.ps1') -DumpTools $Scratch | Out-Null

$tools = Get-Content $Scratch -Encoding UTF8 | Where-Object { $_.Trim() } | ForEach-Object { $_ | ConvertFrom-Json }

function Get-Area($name) {
    switch -Regex ($name) {
        '^(get_libraries|get_master_copies|get_library_types|instantiate_master_copy|open_global_library)$' { return 'libraries' }
        '^(export_objects|import_objects|preview_import)$' { return 'export-import' }
        '^(download_to_plc|get_download_targets)$' { return 'download' }
        '^(hw_|net_|get_devices|get_hardware)' { return 'hardware-network' }
        '^plc_' { return 'plc' }
        '^unified_' { return 'unified' }
        default { return 'general' }
    }
}

$titles = [ordered]@{
    'general'          = @('General', 'Connection, project and session tools.')
    'plc'              = @('PLC software', 'Blocks, data types, tags, tables, external sources, cross references and compile.')
    'hardware-network' = @('Hardware and network', 'Devices, modules, subnets, IO systems and communication connections.')
    'unified'          = @('WinCC Unified', 'Screens, items, tags, scripts, logs, alarms, connections, lists and runtime settings.')
    'libraries'        = @('Libraries', 'The project library, global libraries and master copies.')
    'export-import'    = @('Export and import', 'Blocks, types and tag tables as XML, SIMATIC documents or source files.')
    'download'         = @('Download', 'Download targets and download to a PLC.')
}

function Format-Cell($text) {
    if ($null -eq $text) { return '' }
    return ($text -replace '\|', '\|' -replace '\r?\n', ' ').Trim()
}

function Get-TypeText($p) {
    $t = $p.type
    if ($t -is [array]) { $t = ($t | Where-Object { $_ -ne 'null' }) -join ' or ' }
    if ($t -eq 'array' -and $p.items -and $p.items.type) { $t = "array of $($p.items.type)" }
    return $t
}

New-Item -ItemType Directory -Force $OutDir | Out-Null

$index = New-Object System.Text.StringBuilder
[void]$index.AppendLine('# Tool reference')
[void]$index.AppendLine()
[void]$index.AppendLine('Generated by `tools/make-tool-docs.ps1` from the tool definitions of the server; the `Description` attributes in the code are the source. A tool marked **write** changes the project and is only available when the server runs without `--read-only`; **session** tools only change the connection or the open project/session. Names with `/` in a path are written `%2F`.')
[void]$index.AppendLine()

foreach ($area in $titles.Keys) {
    $group = $tools | Where-Object { (Get-Area $_.name) -eq $area } | Sort-Object name
    if (-not $group) { continue }

    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine("# $($titles[$area][0])")
    [void]$sb.AppendLine()
    [void]$sb.AppendLine($titles[$area][1])
    [void]$sb.AppendLine()
    [void]$sb.AppendLine('| Tool | Kind |')
    [void]$sb.AppendLine('|---|---|')
    foreach ($tool in $group) {
        $kind = if ($tool.annotations.readOnlyHint) { 'read' } elseif ($tool.annotations.destructiveHint) { 'write' } else { 'session' }
        [void]$sb.AppendLine("| [``$($tool.name)``](#$($tool.name)) | $kind |")
    }
    [void]$sb.AppendLine()

    foreach ($tool in $group) {
        [void]$sb.AppendLine("## $($tool.name)")
        [void]$sb.AppendLine()
        [void]$sb.AppendLine((Format-Cell $tool.description))
        [void]$sb.AppendLine()
        $props = @($tool.inputSchema.properties.PSObject.Properties)
        if ($props.Count -gt 0) {
            $required = @($tool.inputSchema.required)
            [void]$sb.AppendLine('| Parameter | Type | Required | Description |')
            [void]$sb.AppendLine('|---|---|---|---|')
            foreach ($prop in $props) {
                $req = if ($required -contains $prop.Name) { 'yes' } else { "no (default ``$($prop.Value.default)``)" }
                [void]$sb.AppendLine("| ``$($prop.Name)`` | $(Get-TypeText $prop.Value) | $req | $(Format-Cell $prop.Value.description) |")
            }
        }
        else {
            [void]$sb.AppendLine('No parameters.')
        }
        [void]$sb.AppendLine()
    }

    $text = $sb.ToString() -replace "`r?`n", "`r`n"
    [IO.File]::WriteAllText((Join-Path $OutDir "$area.md"), $text, (New-Object Text.UTF8Encoding $false))

    $count = @($group).Count
    [void]$index.AppendLine("- [$($titles[$area][0])]($area.md) - $count tools. $($titles[$area][1])")
}

[IO.File]::WriteAllText((Join-Path $OutDir 'README.md'), ($index.ToString() -replace "`r?`n", "`r`n"), (New-Object Text.UTF8Encoding $false))
"written to $OutDir"
